uploads = []
outputs = []

[[generated]]
id = "h6rqTiK7u2gR7_l475c2K"
uri = "file://artifacts/trustpoint-bank/assets/images/icon.png"
type = "image"
title = "trustpoint bank icon"

[[generated]]
id = "eVsXHlPoYEBwlBrGttbXS"
uri = "file://artifacts/trustpoint-bank/assets/images/splash_bg.png"
type = "image"
title = "login background silk"

[[generated]]
id = "0l1OyIAxgXuuESrtV4tqm"
uri = "file://artifacts/trustpoint-bank/assets/images/onboard_security.png"
type = "image"
title = "security shield illustration"

[[generated]]
id = "Skdd1HyX8dxFgb-t-02WQ"
uri = "file://artifacts/trustpoint-bank/assets/images/onboard_speed.png"
type = "image"
title = "speed paper plane illustration"

[[generated]]
id = "2GCLhhikOhNED4hMo_vXF"
uri = "file://artifacts/trustpoint-bank/assets/images/onboard_control.png"
type = "image"
title = "control card phone illustration"

[[generated]]
id = "UDsa_fI_FXxA1pyjxBzKb"
uri = "file://artifacts/trustpoint-bank/assets/images/card_physical.png"
type = "image"
title = "generated_image"

[[generated]]
id = "skGZNCgwqqnie7NEPflPa"
uri = "file://artifacts/trustpoint-bank/assets/images/card_virtual.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Db_GRwW69m5wai_MwH0NX"
uri = "file://artifacts/trustpoint-bank/assets/images/bg_success.png"
type = "image"
title = "generated_image"

[[generated]]
id = "L1qht9hb_OOAScnMrWkGZ"
uri = "file://artifacts/trustpoint-bank/assets/images/bg_dark_surface.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Y32vw_ViJM6LIHhcgAnf2"
uri = "file://artifacts/trustpoint-bank/assets/images/card_physical_new.png"
type = "image"
title = "physical debit card red black"

[[generated]]
id = "1j-ZDRyF_yXg90_YvF4Nw"
uri = "file://artifacts/trustpoint-bank/assets/images/card_virtual_new.png"
type = "image"
title = "virtual debit card black carbon"

[[generated]]
id = "PMQPscEZM_WeAySD5rqje"
uri = "file://artifacts/trustpoint-bank/assets/images/card_premium.png"
type = "image"
title = "premium gold black card"

[[generated]]
id = "GU6jo2PQcKvHLfHGCsw-s"
uri = "file://artifacts/trustpoint-bank/assets/images/icons/nav_home_inactive.png"
type = "image"
title = "home icon grey inactive"

[[generated]]
id = "RyK3EevaULmxLQk6cM3Uh"
uri = "file://artifacts/trustpoint-bank/assets/images/icons/nav_home_active.png"
type = "image"
title = "home icon red active"

[[generated]]
id = "LMNm6y-g4Ntt-bqXCoMG-"
uri = "file://artifacts/trustpoint-bank/assets/images/icons/nav_transfer_inactive.png"
type = "image"
title = "transfer icon grey inactive"

[[generated]]
id = "9WTOQF1xvIkOI92Ncgrk_"
uri = "file://artifacts/trustpoint-bank/assets/images/icons/nav_transfer_active.png"
type = "image"
title = "transfer icon red active"

[[generated]]
id = "LOvq_2w1t1Ahhs2BR_kvm"
uri = "file://artifacts/trustpoint-bank/assets/images/icons/nav_pay_center.png"
type = "image"
title = "diamond pay icon red center"

[[generated]]
id = "EYgkN2EmvQWBeTKqylSMk"
uri = "file://artifacts/trustpoint-bank/assets/images/icons/nav_cards_inactive.png"
type = "image"
title = "cards icon grey inactive"

[[generated]]
id = "iOogS17PV89HaputXh0nF"
uri = "file://artifacts/trustpoint-bank/assets/images/icons/nav_cards_active.png"
type = "image"
title = "cards icon red active"

[[generated]]
id = "4OQfNdi9BZsuBgBIy6gKA"
uri = "file://artifacts/trustpoint-bank/assets/images/dashboard-bg.png"
type = "image"
title = "dashboard bg no bottom lights"
