const colors = {
  dark: {
    background: "#0A0A0A",
    surface: "#1A1A1A",
    card: "#1A1A1A",
    cardForeground: "#F1FAEE",
    primary: "#E63946",
    primaryForeground: "#FFFFFF",
    secondary: "#2A2A2A",
    secondaryForeground: "#F1FAEE",
    muted: "#2A2A2A",
    mutedForeground: "#8E8E93",
    accent: "#E63946",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    text: "#F1FAEE",
    foreground: "#F1FAEE",
    success: "#34C759",
    warning: "#FF9500",
    info: "#007AFF",
    gold: "#FFD60A",
    tint: "#E63946",
    tabBackground: "#111111",
    inputBackground: "#1A1A1A",
    placeholder: "#8E8E93",
    shimmer: "#2A2A2A",
    overlay: "rgba(0,0,0,0.7)",
  },
  light: {
    background: "#F8F9FA",
    surface: "#FFFFFF",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    primary: "#E63946",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F0",
    secondaryForeground: "#1A1A1A",
    muted: "#F0F0F0",
    mutedForeground: "#6C757D",
    accent: "#E63946",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E9ECEF",
    text: "#0A0A0A",
    foreground: "#0A0A0A",
    success: "#34C759",
    warning: "#FF9500",
    info: "#007AFF",
    gold: "#FFB700",
    tint: "#E63946",
    tabBackground: "#FFFFFF",
    inputBackground: "#FFFFFF",
    placeholder: "#6C757D",
    shimmer: "#E9ECEF",
    overlay: "rgba(0,0,0,0.5)",
  },
  radius: 16,
};

export default colors;
